#!/bin/sh
# SPDX-FileCopyrightText: Huawei Inc.
#
# SPDX-License-Identifier: Apache-2.0

# Create directories required by hilogd and hilog
mkdir -p /dev/unix/socket
mkdir -p /data/log/hilog

# Add path to hilog test suite $PATH
PTEST_PATH=$(dirname $(readlink -f $0))
export PATH="${PTEST_PATH}/moduletest/hiviewdfx/hilog:${PATH}"

hilogd &
HILOGD_PID=$!
# Wait a bit so there is a better chance that hilogd is ready for the test
sleep 1

HiLogNDKTest
TEST_RESULT=$?

kill "${HILOGD_PID}"

if test "$TEST_RESULT" -eq 0; then
    echo "PASS: HiLogNDKTest"
else
    echo "FAIL: HiLogNDKTest"
fi
