#!/bin/sh
# SPDX-FileCopyrightText: Huawei Inc.
#
# SPDX-License-Identifier: Apache-2.0

# Start the hilogd service if it is not already running
systemctl start hilogd.service

# Add path to hilog test suite $PATH
PTEST_PATH=$(dirname $(readlink -f $0))
export PATH="${PTEST_PATH}/moduletest/hiviewdfx/hilog:${PATH}"

HiLogNDKTest
TEST_RESULT=$?

if test "$TEST_RESULT" -eq 0; then
    echo "PASS: HiLogNDKTest"
else
    echo "FAIL: HiLogNDKTest"
fi
