#!/bin/sh
# SPDX-FileCopyrightText: Huawei Inc.
#
# SPDX-License-Identifier: Apache-2.0

PTEST_PATH=$(dirname $(readlink -f $0))
cd ${PTEST_PATH}

# Start systemd services as needed
if [ -f systemd-units ] ; then
    for unit in $(cat systemd-units) ; do
        systemctl start $unit
    done
fi

# Component level test fixture setup
if [ -f setup.sh ]; then
    source setup.sh
fi

TEST_RESULT=0

find_tcs() {
    ts=$1
    for tc in $ts/* $ts/*/*Test $ts/*/*_test ; do
        if [ -f $tc -a -x $tc ] ; then
            echo $tc
        fi
    done
}

for ts in unittest moduletest systemtest ; do
    (
        # Test suite level test fixture setup
        if [ -f $ts/setup.sh ]; then
            source $ts/setup.sh
        fi
        for tc in $(find_tcs $ts) ; do
            echo "RUNNING $tc"
            ./$tc
            test_result=$?
            if test "$test_result" -eq 0; then
                echo "PASS: $tc"
            else
                echo "FAIL: $tc"
                TEST_RESULT=1
            fi
        done
        # Test suite level test fixture teardown
        if [ -f $ts/teardown.sh ]; then
            source $ts/teardown.sh
        fi
    )
done

# Component level test fixture teardown
if [ -f setup.sh ]; then
    source teardown.sh
fi

exit $TEST_RESULT
