# SPDX-FileCopyrightText: Huawei Inc.
#
# SPDX-License-Identifier: Apache-2.0

SRC_URI += "file://patches/ace_napi.patch;apply=no;subdir=src"
SRC_URI += "file://patches/base_miscservices_pasteboard.patch;apply=no;subdir=src"
SRC_URI += "file://patches/base_notification_ans_standard.patch;apply=no;subdir=src"
SRC_URI += "file://patches/base_update_updater.patch;apply=no;subdir=src"
SRC_URI += "file://patches/base_usb_usb_manager.patch;apply=no;subdir=src"
SRC_URI += "file://patches/build_lite.patch;apply=no;subdir=src"
SRC_URI += "file://patches/developtools_hdc_standard.patch;apply=no;subdir=src"
SRC_URI += "file://patches/developtools_hiperf.patch;apply=no;subdir=src"
SRC_URI += "file://patches/foundation_aafwk_standard.patch;apply=no;subdir=src"
SRC_URI += "file://patches/foundation_appexecfwk_standard.patch;apply=no;subdir=src"
SRC_URI += "file://patches/foundation_graphic_standard.patch;apply=no;subdir=src"
SRC_URI += "file://patches/productdefine_common.patch;apply=no;subdir=src"
SRC_URI += "file://patches/third_party_libevdev.patch;apply=no;subdir=src"
SRC_URI += "file://patches/third_party_libusb.patch;apply=no;subdir=src"
SRC_URI += "file://patches/third_party_selinux.patch;apply=no;subdir=src"
